---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/micro-vm
  type: udm.Application
  lastVersion: 1.0.1
  children:
  - name: 1.0.1
    type: udm.DeploymentPackage
    deployables:
    - name: ec2
      type: terraform.Module
      inputVariables:
        aws_region: '{{aws_region}}'
        instance_type: '{{instance_type}}'
        ami_id: '{{ami_id}}'
      workspaceName: benoit-test
      applyDestroyOperation: "true"
      file: !file "artifacts/1.0.1/ec2"
  - name: 1.0.0
    type: udm.DeploymentPackage
    deployables:
    - name: ec2
      type: terraform.Module
      inputVariables:
        aws_region: '{{aws_region}}'
        instance_type: '{{instance_type}}'
        ami_id: '{{ami_id}}'
      secretInputVariables:
        secret: "A secret value"
      workspaceName: benoit-test
      applyDestroyOperation: "true"
      file: !file "artifacts/1.0.0/ec2"
